### ISSUE TITLE
PM2.5, CO and O3 stoped working

### ISSUE THREAD

**Issue by rickstaa** [pawkakol1/worlds-air-quality-index#46]
I just stumbled upon a problem: the `Particulate matter (PM2.5)`, `Carbon monoxide (CO)`, and `Ozone (O3)` sensors seem to have stopped working over the past few months. The culprit might be an [API tweak on WAQI's end](https://aqicn.org/json-api/doc/). I'm more than willing to roll up my sleeves and investigate, but given my greenhorn status with HA integrations, I thought it would be good to check if you're already aware of these issues.

### How to reproduce

1. Kick-off HA in a Docker container using [docker-compose](https://docs.docker.com/compose/):

```yml
version: "3.8"

services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    volumes:
      # - /mnt/NAS/video:/media/NAS/video # Mount your NAS video folder.
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
```

2. Install the the [worlds-air-quality-index](https://github.com/pawkakol1/worlds-air-quality-index?tab=readme-ov-file#installation) plugin.
3. Configure the integration with a station that contains the PM2.5, CO, and O3 values (like [this one](https://aqicn.org/city/netherland/haarlem/schipholweg/)).
4. Navigate to the HA entities tab and confirm the absence of these values under the World's Air Quality Index integration.
5. Double-check that these values are supported by the station -> [Station Link](https://api.waqi.info/feed/@7937/?token=d0800a1b8d8b5e5409b7f4fa4010dd3e78636e5f).

![image](https://github.com/pawkakol1/worlds-air-quality-index/assets/17570430/c7cf92a1-56c7-4159-939c-a4032def9e26)
